# PlayerTracker 配置文件
# 傳送等候時間（秒）
teleport-delay-seconds: 10

# 傳送倒計時音效
countdown-sound:
  enabled: true
  sound: BLOCK_NOTE_BLOCK_PLING
  volume: 1.0
  pitch: 1.0

# 傳送中斷音效
interrupted-sound:
  enabled: true
  sound: BLOCK_NOTE_BLOCK_BASS
  volume: 1.0
  pitch: 0.5

# 動作欄顯示
actionbar:
  enabled: true
  message: "傳送倒計時：%seconds%秒"

# 受保護世界（出生點保護範圍所在世界）
protected-world: world

# GUI 更新間隔（秒）
gui-update-interval-seconds: 30

# tracking 持續時間（分鐘）
tracking-duration-seconds: 300

# 經濟系統設置（需要 Vault）
economy:
  track-cost: 50000
  cancel-cost: 70000


# WildRTP 傳送範圍（單位：格）
teleport:
  startRadius: 300
  endRadius: 500


# 家保護設置
home-protection:
  enable: false            # 是否啟用家保護功能（僅檢查玩家的家）
  chunk-range: 1           # 家保護的區塊範圍

# 生成點保護設置
spawn-protection:
  enable: false             # 是否啟用生成點保護功能
  protected-radius: 100.0  # 生成點保護半徑
  protected-world: world   # 生成點保護的世界

# 世界保護設置
world-protection:
  enable: true             # 是否啟用世界保護功能
  untrackable-worlds:      # 不可追蹤的世界列表
    - AfkZone

# Y座標保護設置
y-level-protection:
  enable: true             # 是否啟用Y座標保護功能
  y-level-threshold: -13.0 # Y座標閾值，玩家低於此值時觸發保護
  protected-worlds:        # 應用Y座標保護的世界列表
    - world
# PvPManager Depend setting
pvp-protection:
  enable: true             # 是否啟用PvP狀態保護（PvP關閉的玩家不可被追蹤）